-- Migration 035: track conversation name origin for agent auto-naming.
--
-- NULL    = default/placeholder name (the frontend stuffs the first user
--           message at create time) — an agent-generated title may replace it.
-- 'agent' = title generated by the agent (ACP session_info_update or claude
--           generate_session_title) — a newer agent title may replace it.
-- 'user'  = explicitly renamed by the user — never overwritten by agents.
--
-- Backfill is conservative: every existing non-empty name is marked 'user'
-- because the DB cannot distinguish a deliberate rename from the
-- first-message placeholder; existing names therefore keep current behavior.
ALTER TABLE conversations ADD COLUMN name_source TEXT;
UPDATE conversations SET name_source = 'user' WHERE name != '';
